import streamlit as st
from PIL import Image
import os
from components import render_house_price_dialog, render_income_classification_dialog

# Page configuration
st.set_page_config(
    page_title="Phuc's Portfolio",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Initialize session state for dialog management
if 'show_house_price' not in st.session_state:
    st.session_state.show_house_price = False
if 'show_income_class' not in st.session_state:
    st.session_state.show_income_class = False

# Custom CSS for styling
st.markdown("""
    <style>
    .main {
        background-color: rgb(248, 250, 252);
    }
    .sidebar .sidebar-content {
        background-color: rgb(2, 70, 131);
    }
    h1 {
        color: rgb(44, 172, 173);
        font-family: 'Trebuchet MS', sans-serif;
    }
    h2 {
        color: rgb(117, 200, 202);
        font-family: 'Trebuchet MS', sans-serif;
    }
    h3 {
        color: rgb(117, 200, 202);
        font-family: 'Trebuchet MS', sans-serif;
    }
    .stMarkdown {
        color: #002b5b;
    }
    </style>
    """, unsafe_allow_html=True)

# Sidebar - About Me Section
with st.sidebar:
    # Profile Picture
    if os.path.exists("images/temp_ava.jpg"):
        profile_img = Image.open("images/temp_ava.jpg")
        st.image(profile_img, width=200)
    
    st.markdown("## About Me")
    st.write("""
    Hello, I'm Phúc, a student who pursuing Bachelor of Data Science at University of Science, 
    Vietnam National University - Ho Chi Minh. I want to be a Data Scientist or an AI Engineering 
    after graduating, and now I'm looking for an Internship job.
    """)
    
    st.markdown("## Contact")
    st.write("📧 Email: dmphuc04.work@gmail.com")
    st.write("📱 Phone: (+84)...")
    st.write("💼 [LinkedIn: phuc-dm](https://www.linkedin.com/in/phuc-dm/)")
    st.write("👥 [Facebook: Đặng Minh Phúc](https://www.facebook.com/Tis51T/)")

# Main Content
st.title("🎯 Phuc's Portfolio")

col1, col2 = st.columns(2)

with col2:
    st.header("Projects")

    with st.expander("Horror Story Generator"):
        st.markdown("**Background:**")
        st.write("""
        I'm a huge fan of horror stories! I love listening to them on YouTube and reading them on Reddit. 
        However, with the sheer number of stories out there, I started wondering - are they all written 
        by humans, or are some generated by AI? That curiosity led me to an exciting project: I decided 
        to crawl horror stories, fine-tune a model, and see if AI could craft terrifying tales of its own.
        """)
        st.markdown("**Skills:** Web Scrapping, NLP, Model Fine-tuning, Prompting")

    with st.expander("Human Status Detection"):
        st.markdown("**Background:**")
        st.write("""
        This project was my final assignment for the Pattern Recognition course. It focused on detecting 
        a person's mental or physical state using electroencephalogram (EEG) data. By analyzing brainwave 
        patterns, the goal was to classify different states using machine learning techniques. The project 
        involved preprocessing EEG signals, extracting meaningful features, and experimenting with various models.
        """)
        st.markdown("**Skills:** Signal Processing, Pattern Recognition, Machine Learning")

    with st.expander("House Price Prediction in Ho Chi Minh city"):
        st.markdown("**Background:**")
        st.write("""
        This project was my final assignment for the Introduction to Data Science course. As the name 
        suggests, the goal was to determine the best model for predicting house prices in Ho Chi Minh City. 
        The dataset spans from 2022 and includes historical data from previous years.
        """)
        st.markdown("**Skills:** Web Scrapping, Data Cleaning, Data Preprocessing, Machine Learning")
        
        if st.button("View More", key="house_price"):
            st.session_state.show_house_price = True

    with st.expander("Income Type Classification"):
        st.markdown("**Background:**")
        st.write("""
        Every day, I watched economic news on TV, covering topics like GDP, GNI, and other economic 
        indicators of Vietnam. One day, a question crossed my mind: Could I determine a country's income 
        classification based solely on its economic indices? To find out, I decided to collect a dataset 
        and build a model to answer this question.
        """)
        st.markdown("**Skills:** APIs, Exploratory Data Analysis, Machine Learning")
        
        if st.button("View More", key="income_class"):
            st.session_state.show_income_class = True
            
    with st.expander("Vietnamese Graduated Highschool Student Score in Ho Chi Minh city, 2022"):
        st.markdown("**Background:**")
        st.write("""
        After completing my graduation exam and receiving my scores, I became curious about the educational 
        trends in my city in 2022. To explore this further, my friend and I decided to crawl all student 
        results from the Searching Result website (which is now disabled) and analyze the data to uncover 
        meaningful insights.
        """)
        st.markdown("**Skills:** Web Scrapping, Data Cleaning, Exploratory Data Analysis")

# Footer
st.markdown("---")
st.markdown("""
<div style='text-align: center; color: #666;'>
    <p>© 2025 Phuc's Portfolio | Built with Streamlit 🚀</p>
</div>
""", unsafe_allow_html=True)

# Dialog for House Price Prediction
@st.dialog("🏠 House Price Prediction in Ho Chi Minh City", width="large")
def show_house_price_dialog():
    render_house_price_dialog()

# Dialog for Income Type Classification
@st.dialog("💰 Income Type Classification", width="large")
def show_income_class_dialog():
    render_income_classification_dialog()

# Show dialogs based on session state
if st.session_state.show_house_price:
    show_house_price_dialog()

if st.session_state.show_income_class:
    show_income_class_dialog()
