import streamlit as st

PROJECTS = [
        {
        "title": "Searching Film Website",
        "description": """In the age of streaming, finding where to watch a specific movie or TV show can be a daunting task. With countless platforms available, I embarked on a project to create a web application that allows users to search for films and instantly discover which streaming services offer them. This tool aims to simplify the search process and enhance the viewing experience.""",
        "skills": "Web Scrapping, Data Cleaning, Data Preprocessing, Machine Learning",
        "date": "November 2025",
    },
        {"title": "Sarcasm Detection",
        "description": """Sarcasm is a nuanced form of communication that often poses challenges for natural language processing (NLP) systems. To tackle this, I developed a sarcasm detection model that can accurately identify sarcastic remarks in text. This project involved collecting a diverse dataset, preprocessing the text data, and experimenting with various machine learning algorithms to achieve optimal performance.""",
        "skills": "NLP, Machine Learning, Data Preprocessing",
        "date": "December 2024",
    },
            {
        "title": "Human Status Detection",
        "description": """This project was my final assignment for the Pattern Recognition course. It focused on detecting a person's mental or physical state using electroencephalogram (EEG) data. By analyzing brainwave patterns, the goal was to classify different states using machine learning techniques. The project involved preprocessing EEG signals, extracting meaningful features, and experimenting with various models.""",
        "skills": "Signal Processing, Pattern Recognition, Machine Learning",
        "date": "December 2024",
    },
            {
        "title": "Horror Story Generator",
        "description": """I'm a huge fan of horror stories! I love listening to them on YouTube and reading them on Reddit. However, with the sheer number of stories out there, I started wondering - are they all written by humans, or are some generated by AI? That curiosity led me to an exciting project: I decided to crawl horror stories, feed these to AI and see if it could craft terrifying tales of its own.""",
        "skills": "Web Scrapping, NLP, Model Fine-tuning, Prompting",
        "date": "May 2025",
    },

    {
        "title": "House Price Prediction",
        "description": """This project was my final assignment for the Introduction to Data Science course. As the name suggests, the goal was to determine the best model for predicting house prices in Ho Chi Minh City. The dataset spans from 2022 and includes historical data from previous years.""",
        "skills": "Data Cleaning, Data Preprocessing, Machine Learning",
        "date": "May 2024"
    },

    {
        "title": "Income Type Classification",
        "description": """Every day, I watched economic news on TV, covering topics like GDP, GNI, and other economic indicators of Vietnam. One day, a question crossed my mind: Could I determine a country's income classification based solely on its economic indices? To find out, I decided to collect a dataset and build a model to answer this question.""",
        "skills": "APIs, Exploratory Data Analysis, Machine Learning",
        "date": "August 2024"
    },
    {
        "title": "Graduated Score Dashboard",
        "description": """After completing my graduation exam and receiving my scores, I became curious about the educational trends in my city in 2022. I crawled student results and analyzed them to uncover meaningful insights.""",
        "skills": "Web Scrapping, Data Cleaning, Exploratory Data Analysis",
        "date": "September 2022",
    },

]

def render_projects():
    project_per_row = 2
    for i in range(0, len(PROJECTS), project_per_row):
        cols = st.columns(project_per_row)
        for j in range(project_per_row):
            if i + j < len(PROJECTS):
                project = PROJECTS[i + j]
                with cols[j]:
                    with st.expander(project["title"]):
                        st.markdown(f"""<span style='color: {st.session_state.get('primary','') or '#FFCC66'}; font-weight: 700;'>Background:</span> 
                                    {project["description"]}
                                    """, unsafe_allow_html=True)

                        st.markdown(f"""<span style='color: {st.session_state.get('primary','') or '#FFCC66'}; font-weight: 700;'>Skills:</span> 
                                    {project["skills"]}
                                    """, unsafe_allow_html=True)

                        st.markdown(f"""<span style='color: {st.session_state.get('primary','') or '#FFCC66'}; font-weight: 700;'>Duration:</span> 
                                    {project["date"]}
                                    """, unsafe_allow_html=True)
