import streamlit as st

def render_projects():
    """Render the projects column (right side). This sets st.session_state.open_dialog when View More is clicked."""
    st.header("Projects")

    with st.expander("Horror Story Generator"):
        st.markdown(f"<span style='color: {st.session_state.get('primary','') or '#FFCC66'}; font-weight: 700;'>Background:</span>", unsafe_allow_html=True)
        st.write("""
        I'm a huge fan of horror stories! I love listening to them on YouTube and reading them on Reddit. 
        However, with the sheer number of stories out there, I started wondering - are they all written 
        by humans, or are some generated by AI? That curiosity led me to an exciting project: I decided 
        to crawl horror stories, fine-tune a model, and see if AI could craft terrifying tales of its own.
        """)
        st.markdown("**Skills:** Web Scrapping, NLP, Model Fine-tuning, Prompting")

    with st.expander("Human Status Detection"):
        st.markdown(f"<span style='color: {st.session_state.get('primary','') or '#FFCC66'}; font-weight: 700;'>Background:</span>", unsafe_allow_html=True)
        st.write("""
        This project was my final assignment for the Pattern Recognition course. It focused on detecting 
        a person's mental or physical state using electroencephalogram (EEG) data. By analyzing brainwave 
        patterns, the goal was to classify different states using machine learning techniques. The project 
        involved preprocessing EEG signals, extracting meaningful features, and experimenting with various models.
        """)
        st.markdown("**Skills:** Signal Processing, Pattern Recognition, Machine Learning")

    with st.expander("House Price Prediction in Ho Chi Minh city"):
        st.markdown(f"<span style='color: {st.session_state.get('primary','') or '#FFCC66'}; font-weight: 700;'>Background:</span>", unsafe_allow_html=True)
        st.write("""
        This project was my final assignment for the Introduction to Data Science course. As the name 
        suggests, the goal was to determine the best model for predicting house prices in Ho Chi Minh City. 
        The dataset spans from 2022 and includes historical data from previous years.
        """)
        st.markdown("**Skills:** Web Scrapping, Data Cleaning, Data Preprocessing, Machine Learning")
        if st.button("View More", key="house_price"):
            st.session_state.open_dialog = 'house'

    with st.expander("Income Type Classification"):
        st.markdown(f"<span style='color: {st.session_state.get('primary','') or '#FFCC66'}; font-weight: 700;'>Background:</span>", unsafe_allow_html=True)
        st.write("""
        Every day, I watched economic news on TV, covering topics like GDP, GNI, and other economic 
        indicators of Vietnam. One day, a question crossed my mind: Could I determine a country's income 
        classification based solely on its economic indices? To find out, I decided to collect a dataset 
        and build a model to answer this question.
        """)
        st.markdown("**Skills:** APIs, Exploratory Data Analysis, Machine Learning")
        if st.button("View More", key="income_class"):
            st.session_state.open_dialog = 'income'

    with st.expander("Vietnamese Graduated Highschool Student Score in Ho Chi Minh city, 2022"):
        st.markdown(f"<span style='color: {st.session_state.get('primary','') or '#FFCC66'}; font-weight: 700;'>Background:</span>", unsafe_allow_html=True)
        st.write("""
        After completing my graduation exam and receiving my scores, I became curious about the educational 
        trends in my city in 2022. I crawled student results and analyzed them to uncover meaningful insights.
        """)
        st.markdown("**Skills:** Web Scrapping, Data Cleaning, Exploratory Data Analysis")
